import type {
  User,
  Exam,
  Rubric,
  Submission,
  Evaluation,
  CalibrationSample,
  AuditLog,
  AIUsageRecord,
  SystemSettings,
} from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'admin-001',
    email: 'admin@university.edu',
    name: 'Dr. Priya Nair',
    role: 'admin',
    department: 'Information Technology',
    avatarInitials: 'PN',
    createdAt: '2024-07-15T08:00:00Z',
  },
  {
    id: 'faculty-001',
    email: 'prof.sharma@university.edu',
    name: 'Prof. Arjun Sharma',
    role: 'faculty',
    facultyId: 'FAC-2021-001',
    department: 'Computer Science',
    avatarInitials: 'AS',
    createdAt: '2024-07-15T08:00:00Z',
  },
  {
    id: 'faculty-002',
    email: 'dr.chen@university.edu',
    name: 'Dr. Mei Chen',
    role: 'faculty',
    facultyId: 'FAC-2021-002',
    department: 'Mathematics',
    avatarInitials: 'MC',
    createdAt: '2024-07-15T08:00:00Z',
  },
  {
    id: 'student-001',
    email: 'alice.johnson@student.edu',
    name: 'Alice Johnson',
    role: 'student',
    studentId: 'STU-2023-001',
    department: 'Computer Science',
    avatarInitials: 'AJ',
    calibrated: true,
    createdAt: '2024-08-01T10:00:00Z',
  },
  {
    id: 'student-002',
    email: 'bob.smith@student.edu',
    name: 'Bob Smith',
    role: 'student',
    studentId: 'STU-2023-002',
    department: 'Computer Science',
    avatarInitials: 'BS',
    calibrated: true,
    createdAt: '2024-08-01T10:00:00Z',
  },
  {
    id: 'student-003',
    email: 'carol.white@student.edu',
    name: 'Carol White',
    role: 'student',
    studentId: 'STU-2023-003',
    department: 'Mathematics',
    avatarInitials: 'CW',
    calibrated: false,
    createdAt: '2024-08-02T09:00:00Z',
  },
  {
    id: 'student-004',
    email: 'david.kumar@student.edu',
    name: 'David Kumar',
    role: 'student',
    studentId: 'STU-2023-004',
    department: 'Computer Science',
    avatarInitials: 'DK',
    calibrated: true,
    createdAt: '2024-08-02T09:00:00Z',
  },
  {
    id: 'student-005',
    email: 'eve.martinez@student.edu',
    name: 'Eve Martinez',
    role: 'student',
    studentId: 'STU-2023-005',
    department: 'Mathematics',
    avatarInitials: 'EM',
    calibrated: false,
    createdAt: '2024-08-03T11:00:00Z',
  },
];

export const DEMO_CREDENTIALS: Record<string, string> = {
  'admin@university.edu': 'demo123',
  'prof.sharma@university.edu': 'demo123',
  'dr.chen@university.edu': 'demo123',
  'alice.johnson@student.edu': 'demo123',
  'bob.smith@student.edu': 'demo123',
  'carol.white@student.edu': 'demo123',
  'david.kumar@student.edu': 'demo123',
  'eve.martinez@student.edu': 'demo123',
};

export const DEMO_EXAMS: Exam[] = [
  {
    id: 'exam-001',
    title: 'Data Structures and Algorithms',
    code: 'CS201',
    subject: 'Computer Science',
    facultyId: 'faculty-001',
    facultyName: 'Prof. Arjun Sharma',
    date: '2024-11-15',
    duration: 180,
    maxMarks: 30,
    status: 'ACTIVE',
    studentIds: ['student-001', 'student-002', 'student-004'],
    rubricId: 'rubric-001',
    description:
      'Mid-semester examination covering stacks, queues, trees, and algorithm analysis.',
    createdAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'exam-002',
    title: 'Linear Algebra',
    code: 'MTH301',
    subject: 'Mathematics',
    facultyId: 'faculty-002',
    facultyName: 'Dr. Mei Chen',
    date: '2024-11-18',
    duration: 120,
    maxMarks: 50,
    status: 'ACTIVE',
    studentIds: ['student-003', 'student-005'],
    rubricId: 'rubric-002',
    description: 'Final examination on vector spaces, linear transformations, and eigenvalues.',
    createdAt: '2024-09-05T14:00:00Z',
  },
  {
    id: 'exam-003',
    title: 'Object-Oriented Programming',
    code: 'CS301',
    subject: 'Computer Science',
    facultyId: 'faculty-001',
    facultyName: 'Prof. Arjun Sharma',
    date: '2024-12-01',
    duration: 150,
    maxMarks: 40,
    status: 'DRAFT',
    studentIds: ['student-001', 'student-002'],
    description: 'End-semester examination on OOP principles, design patterns, and SOLID.',
    createdAt: '2024-10-15T10:00:00Z',
  },
];

export const DEMO_RUBRICS: Rubric[] = [
  {
    id: 'rubric-001',
    examId: 'exam-001',
    questions: [
      {
        id: 'rq-001-1',
        number: '1',
        questionText:
          'Explain the difference between a Stack and a Queue. Provide one real-world application of each.',
        maxMarks: 10,
        criteria: [
          {
            id: 'rc-001-1-1',
            description: 'Correct definition of Stack (LIFO principle)',
            maxMarks: 2,
            guidance: 'Must mention Last-In-First-Out. Award 1 mark for partial explanation.',
          },
          {
            id: 'rc-001-1-2',
            description: 'Correct definition of Queue (FIFO principle)',
            maxMarks: 2,
            guidance: 'Must mention First-In-First-Out. Award 1 mark for partial explanation.',
          },
          {
            id: 'rc-001-1-3',
            description: 'Valid real-world application of Stack',
            maxMarks: 2,
            guidance:
              'Accept: browser history, undo/redo, function call stack, expression evaluation.',
          },
          {
            id: 'rc-001-1-4',
            description: 'Valid real-world application of Queue',
            maxMarks: 2,
            guidance: 'Accept: print spooler, CPU scheduling, BFS, customer service queues.',
          },
          {
            id: 'rc-001-1-5',
            description: 'Clarity, structure, and quality of explanation',
            maxMarks: 2,
            guidance: 'Award full marks for clearly written, well-organised response.',
          },
        ],
      },
      {
        id: 'rq-001-2a',
        number: '2a',
        questionText: 'Write pseudocode for a Binary Search algorithm.',
        maxMarks: 8,
        criteria: [
          {
            id: 'rc-001-2a-1',
            description: 'Correct initialisation of low, mid, high pointers',
            maxMarks: 2,
          },
          {
            id: 'rc-001-2a-2',
            description: 'Correct loop condition and mid-point calculation',
            maxMarks: 3,
          },
          {
            id: 'rc-001-2a-3',
            description: 'Correct return/output for found and not-found cases',
            maxMarks: 3,
          },
        ],
      },
      {
        id: 'rq-001-2b',
        number: '2b',
        questionText:
          'State the time complexity of your Binary Search algorithm and justify your answer.',
        maxMarks: 4,
        criteria: [
          {
            id: 'rc-001-2b-1',
            description: 'Correct time complexity: O(log n)',
            maxMarks: 2,
          },
          {
            id: 'rc-001-2b-2',
            description:
              'Correct justification (search space halves each iteration)',
            maxMarks: 2,
          },
        ],
      },
      {
        id: 'rq-001-3',
        number: '3',
        questionText:
          'Insert the values 15, 10, 20, 8, 12, 25, 18 into a Binary Search Tree. Draw the resulting tree and state the in-order traversal sequence.',
        maxMarks: 8,
        criteria: [
          {
            id: 'rc-001-3-1',
            description: 'Correct BST structure (root 15, correct left/right subtrees)',
            maxMarks: 4,
            guidance: 'Award 2 marks if structure is partially correct.',
          },
          {
            id: 'rc-001-3-2',
            description: 'Correct in-order traversal: 8, 10, 12, 15, 18, 20, 25',
            maxMarks: 2,
          },
          {
            id: 'rc-001-3-3',
            description: 'Clear diagram description or drawing',
            maxMarks: 2,
          },
        ],
      },
    ],
    createdAt: '2024-09-10T10:00:00Z',
    updatedAt: '2024-09-10T10:00:00Z',
  },
  {
    id: 'rubric-002',
    examId: 'exam-002',
    questions: [
      {
        id: 'rq-002-1',
        number: '1',
        questionText:
          'Define a vector space. Verify whether the set of all 2×2 matrices forms a vector space under standard matrix addition and scalar multiplication.',
        maxMarks: 12,
        criteria: [
          {
            id: 'rc-002-1-1',
            description: 'Correct definition of a vector space with all 8 axioms',
            maxMarks: 4,
          },
          {
            id: 'rc-002-1-2',
            description: 'Correct verification of closure under addition',
            maxMarks: 3,
          },
          {
            id: 'rc-002-1-3',
            description: 'Correct verification of closure under scalar multiplication',
            maxMarks: 3,
          },
          {
            id: 'rc-002-1-4',
            description: 'Correct identification of zero element and additive inverse',
            maxMarks: 2,
          },
        ],
      },
      {
        id: 'rq-002-2',
        number: '2',
        questionText:
          'Find the eigenvalues and eigenvectors of the matrix A = [[3, 1], [0, 2]].',
        maxMarks: 15,
        criteria: [
          {
            id: 'rc-002-2-1',
            description: 'Correct characteristic equation setup: det(A - λI) = 0',
            maxMarks: 4,
          },
          {
            id: 'rc-002-2-2',
            description: 'Correct eigenvalues: λ₁ = 3, λ₂ = 2',
            maxMarks: 4,
          },
          {
            id: 'rc-002-2-3',
            description: 'Correct eigenvector for λ₁ = 3',
            maxMarks: 3,
          },
          {
            id: 'rc-002-2-4',
            description: 'Correct eigenvector for λ₂ = 2',
            maxMarks: 4,
          },
        ],
      },
    ],
    createdAt: '2024-09-12T14:00:00Z',
    updatedAt: '2024-09-12T14:00:00Z',
  },
];

const HANDWRITING_IMAGES = [
  'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=1100&fit=crop&auto=format',
  'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=800&h=1100&fit=crop&auto=format',
  'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800&h=1100&fit=crop&auto=format',
  'https://images.unsplash.com/photo-1471107191679-f26174d2d41e?w=800&h=1100&fit=crop&auto=format',
  'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&h=1100&fit=crop&auto=format',
];

export const DEMO_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-001',
    studentId: 'student-001',
    studentName: 'Alice Johnson',
    examId: 'exam-001',
    submittedAt: '2024-11-15T11:45:00Z',
    pages: [
      {
        id: 'page-001-1',
        pageNumber: 1,
        imageUrl: HANDWRITING_IMAGES[0],
        thumbnailUrl: HANDWRITING_IMAGES[0].replace('w=800&h=1100', 'w=200&h=280'),
      },
      {
        id: 'page-001-2',
        pageNumber: 2,
        imageUrl: HANDWRITING_IMAGES[2],
        thumbnailUrl: HANDWRITING_IMAGES[2].replace('w=800&h=1100', 'w=200&h=280'),
      },
      {
        id: 'page-001-3',
        pageNumber: 3,
        imageUrl: HANDWRITING_IMAGES[4],
        thumbnailUrl: HANDWRITING_IMAGES[4].replace('w=800&h=1100', 'w=200&h=280'),
      },
    ],
    status: 'FACULTY_REVIEW',
    evaluationId: 'eval-001',
    pageCount: 3,
  },
  {
    id: 'sub-002',
    studentId: 'student-002',
    studentName: 'Bob Smith',
    examId: 'exam-001',
    submittedAt: '2024-11-15T12:10:00Z',
    pages: [
      {
        id: 'page-002-1',
        pageNumber: 1,
        imageUrl: HANDWRITING_IMAGES[1],
        thumbnailUrl: HANDWRITING_IMAGES[1].replace('w=800&h=1100', 'w=200&h=280'),
      },
      {
        id: 'page-002-2',
        pageNumber: 2,
        imageUrl: HANDWRITING_IMAGES[3],
        thumbnailUrl: HANDWRITING_IMAGES[3].replace('w=800&h=1100', 'w=200&h=280'),
      },
    ],
    status: 'AI_COMPLETE',
    evaluationId: 'eval-002',
    pageCount: 2,
  },
  {
    id: 'sub-003',
    studentId: 'student-004',
    studentName: 'David Kumar',
    examId: 'exam-001',
    submittedAt: '2024-11-15T11:55:00Z',
    pages: [
      {
        id: 'page-003-1',
        pageNumber: 1,
        imageUrl: HANDWRITING_IMAGES[2],
        thumbnailUrl: HANDWRITING_IMAGES[2].replace('w=800&h=1100', 'w=200&h=280'),
      },
      {
        id: 'page-003-2',
        pageNumber: 2,
        imageUrl: HANDWRITING_IMAGES[0],
        thumbnailUrl: HANDWRITING_IMAGES[0].replace('w=800&h=1100', 'w=200&h=280'),
      },
      {
        id: 'page-003-3',
        pageNumber: 3,
        imageUrl: HANDWRITING_IMAGES[4],
        thumbnailUrl: HANDWRITING_IMAGES[4].replace('w=800&h=1100', 'w=200&h=280'),
      },
    ],
    status: 'PUBLISHED',
    evaluationId: 'eval-003',
    pageCount: 3,
  },
];

export const DEMO_EVALUATIONS: Evaluation[] = [
  {
    id: 'eval-001',
    submissionId: 'sub-001',
    studentId: 'student-001',
    studentName: 'Alice Johnson',
    examId: 'exam-001',
    examTitle: 'Data Structures and Algorithms (CS201)',
    transcription:
      'Q1: A stack is a linear data structure that follows the Last-In-First-Out (LIFO) principle. This means the last element added is the first to be removed. A real-world application is the browser back button — pages visited are pushed to a stack and popped when you go back. A queue is a linear data structure following First-In-First-Out (FIFO). Elements are added at the rear and removed from the front. An application is a printer spooler — print jobs are processed in the order they arrive. Q2a: FUNCTION BinarySearch(arr, target): low = 0; high = length(arr) - 1; WHILE low <= high: mid = (low + high) / 2; IF arr[mid] == target: RETURN mid; ELSE IF arr[mid] < target: low = mid + 1; ELSE: high = mid - 1; RETURN -1. Q2b: Time complexity is O(log n) because each iteration halves the search space, resulting in at most log₂(n) comparisons for n elements. Q3: BST with root 15. Left subtree: 10 (left: 8, right: 12). Right subtree: 20 (left: 18, right: 25). In-order traversal: 8, 10, 12, 15, 18, 20, 25.',
    questions: [
      {
        id: 'eq-001-1',
        questionNumber: '1',
        studentAnswer:
          'A stack is a linear data structure that follows the Last-In-First-Out (LIFO) principle. The last element added is the first to be removed. Real-world application: browser back button — pages are pushed and popped. A queue follows First-In-First-Out (FIFO). Elements are enqueued at the rear and dequeued from the front. Application: printer spooler — jobs processed in order they arrive.',
        answerSummary:
          'Correctly defined both stack (LIFO) and queue (FIFO) with appropriate real-world examples.',
        criteriaScores: [
          { criterionId: 'rc-001-1-1', criterion: 'Correct definition of Stack (LIFO)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-2', criterion: 'Correct definition of Queue (FIFO)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-3', criterion: 'Valid real-world application of Stack', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-4', criterion: 'Valid real-world application of Queue', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-5', criterion: 'Clarity and quality of explanation', awarded: 2, max: 2 },
        ],
        totalAwarded: 10,
        maxMarks: 10,
        feedback:
          'Excellent response. Both data structures defined accurately with correct LIFO/FIFO terminology and relevant real-world examples.',
        confidence: 0.94,
        confidenceLevel: 'HIGH',
        flags: [],
        pageStart: 1,
        pageEnd: 1,
      },
      {
        id: 'eq-001-2a',
        questionNumber: '2a',
        studentAnswer:
          'FUNCTION BinarySearch(arr, target): low = 0; high = length(arr) - 1; WHILE low <= high: mid = floor((low + high) / 2); IF arr[mid] == target: RETURN mid; ELSE IF arr[mid] < target: low = mid + 1; ELSE: high = mid - 1; RETURN -1.',
        answerSummary: 'Correct binary search pseudocode with proper pointer initialisation and loop logic.',
        criteriaScores: [
          { criterionId: 'rc-001-2a-1', criterion: 'Correct initialisation of low, mid, high', awarded: 2, max: 2 },
          { criterionId: 'rc-001-2a-2', criterion: 'Correct loop condition and mid-point', awarded: 3, max: 3 },
          { criterionId: 'rc-001-2a-3', criterion: 'Correct return for found and not-found', awarded: 3, max: 3 },
        ],
        totalAwarded: 8,
        maxMarks: 8,
        feedback:
          'Perfect pseudocode. All pointers correctly initialised, loop condition correct, and both return cases handled.',
        confidence: 0.91,
        confidenceLevel: 'HIGH',
        flags: [],
        pageStart: 2,
        pageEnd: 2,
      },
      {
        id: 'eq-001-2b',
        questionNumber: '2b',
        studentAnswer:
          'Time complexity is O(log n). Each iteration halves the search space, so for n elements we need at most log₂(n) comparisons.',
        answerSummary: 'Correctly states O(log n) with valid justification.',
        criteriaScores: [
          { criterionId: 'rc-001-2b-1', criterion: 'Correct complexity: O(log n)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-2b-2', criterion: 'Correct justification', awarded: 2, max: 2 },
        ],
        totalAwarded: 4,
        maxMarks: 4,
        feedback: 'Correct. Clear justification with the halving argument.',
        confidence: 0.97,
        confidenceLevel: 'HIGH',
        flags: [],
        pageStart: 2,
        pageEnd: 2,
      },
      {
        id: 'eq-001-3',
        questionNumber: '3',
        studentAnswer:
          'BST: Root=15. Left child=10 (left=8, right=12). Right child=20 (left=18, right=25). In-order: 8, 10, 12, 15, 18, 20, 25.',
        answerSummary: 'Correct BST structure and in-order traversal. Diagram partially unclear.',
        criteriaScores: [
          { criterionId: 'rc-001-3-1', criterion: 'Correct BST structure', awarded: 4, max: 4 },
          { criterionId: 'rc-001-3-2', criterion: 'Correct in-order traversal', awarded: 2, max: 2 },
          { criterionId: 'rc-001-3-3', criterion: 'Clear diagram', awarded: 1, max: 2 },
        ],
        totalAwarded: 7,
        maxMarks: 8,
        feedback:
          'BST construction correct. Traversal sequence correct. The drawn diagram is partially unclear — deducting 1 mark on diagram quality.',
        confidence: 0.78,
        confidenceLevel: 'MEDIUM',
        flags: ['DIAGRAM_DETECTED', 'UNCLEAR_HANDWRITING'],
        pageStart: 3,
        pageEnd: 3,
      },
    ],
    totalMarks: 29,
    maxMarks: 30,
    overallConfidence: 0.9,
    overallConfidenceLevel: 'HIGH',
    flags: ['DIAGRAM_DETECTED'],
    status: 'FACULTY_REVIEW',
    aiGeneratedAt: '2024-11-15T12:02:00Z',
    version: 1,
  },
  {
    id: 'eval-002',
    submissionId: 'sub-002',
    studentId: 'student-002',
    studentName: 'Bob Smith',
    examId: 'exam-001',
    examTitle: 'Data Structures and Algorithms (CS201)',
    transcription:
      'Q1: Stack — LIFO, elements added and removed from same end (top). Used in function call stack in programming. Queue — FIFO, elements added at back, removed from front. Used in breadth-first search. Q2a: BinarySearch(arr, x): lo=0, hi=n-1; while lo<=hi: m=(lo+hi)/2; if arr[m]==x return m; if arr[m]<x lo=m+1 else hi=m-1; return -1. Q2b: O(log n) — halves search space each step. Q3: [diagram appears unclear] Root is 15, left is 10 with children 8 and 12, right is 20 with children 18 and 25. In-order: 8 10 12 15 18 20 25.',
    questions: [
      {
        id: 'eq-002-1',
        questionNumber: '1',
        studentAnswer:
          'Stack uses LIFO — Last In, First Out. Elements added and removed from same end called top. Used in function call stack. Queue uses FIFO — elements added at back, removed from front. Used in BFS algorithm.',
        answerSummary: 'Definitions partially correct. Applications valid but brief.',
        criteriaScores: [
          { criterionId: 'rc-001-1-1', criterion: 'Correct definition of Stack (LIFO)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-2', criterion: 'Correct definition of Queue (FIFO)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-3', criterion: 'Valid real-world application of Stack', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-4', criterion: 'Valid real-world application of Queue', awarded: 1, max: 2 },
          { criterionId: 'rc-001-1-5', criterion: 'Clarity and quality of explanation', awarded: 1, max: 2 },
        ],
        totalAwarded: 8,
        maxMarks: 10,
        feedback:
          'Good definitions. Stack application (function call stack) is excellent. Queue application (BFS) is valid but a more concrete real-world example (e.g. printer queue) would be stronger.',
        confidence: 0.86,
        confidenceLevel: 'MEDIUM',
        flags: [],
        pageStart: 1,
        pageEnd: 1,
      },
      {
        id: 'eq-002-2a',
        questionNumber: '2a',
        studentAnswer:
          'BinarySearch(arr, x): lo=0, hi=n-1; while lo<=hi: m=(lo+hi)/2; if arr[m]==x return m; if arr[m]<x lo=m+1 else hi=m-1; return -1.',
        answerSummary: 'Correct binary search. Uses compact notation.',
        criteriaScores: [
          { criterionId: 'rc-001-2a-1', criterion: 'Correct initialisation', awarded: 2, max: 2 },
          { criterionId: 'rc-001-2a-2', criterion: 'Correct loop and mid-point', awarded: 2, max: 3 },
          { criterionId: 'rc-001-2a-3', criterion: 'Correct return statements', awarded: 3, max: 3 },
        ],
        totalAwarded: 7,
        maxMarks: 8,
        feedback:
          'Algorithm is correct. Minor issue: mid-point calculation should use floor() explicitly to avoid floating-point issues. Deducting 1 mark.',
        confidence: 0.88,
        confidenceLevel: 'MEDIUM',
        flags: [],
        pageStart: 1,
        pageEnd: 2,
      },
      {
        id: 'eq-002-2b',
        questionNumber: '2b',
        studentAnswer: 'O(log n) — halves search space each step.',
        answerSummary: 'Correct complexity, minimal justification.',
        criteriaScores: [
          { criterionId: 'rc-001-2b-1', criterion: 'Correct complexity: O(log n)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-2b-2', criterion: 'Correct justification', awarded: 1, max: 2 },
        ],
        totalAwarded: 3,
        maxMarks: 4,
        feedback:
          'Complexity is correct. Justification is too brief — needs to mention the relationship between halving and logarithmic growth more explicitly.',
        confidence: 0.9,
        confidenceLevel: 'HIGH',
        flags: [],
        pageStart: 2,
        pageEnd: 2,
      },
      {
        id: 'eq-002-3',
        questionNumber: '3',
        studentAnswer:
          'Root is 15. Left subtree: 10 → 8 (left), 12 (right). Right subtree: 20 → 18 (left), 25 (right). In-order: 8 10 12 15 18 20 25.',
        answerSummary: 'Correct BST. Diagram was unclear in original script.',
        criteriaScores: [
          { criterionId: 'rc-001-3-1', criterion: 'Correct BST structure', awarded: 4, max: 4 },
          { criterionId: 'rc-001-3-2', criterion: 'Correct in-order traversal', awarded: 2, max: 2 },
          { criterionId: 'rc-001-3-3', criterion: 'Clear diagram', awarded: 1, max: 2 },
        ],
        totalAwarded: 7,
        maxMarks: 8,
        feedback: 'BST correct. Traversal correct. Drawn diagram was unclear — please verify.',
        confidence: 0.71,
        confidenceLevel: 'LOW',
        flags: ['DIAGRAM_DETECTED', 'UNCLEAR_HANDWRITING', 'LOW_IMAGE_QUALITY'],
        pageStart: 2,
        pageEnd: 2,
      },
    ],
    totalMarks: 25,
    maxMarks: 30,
    overallConfidence: 0.84,
    overallConfidenceLevel: 'MEDIUM',
    flags: ['DIAGRAM_DETECTED', 'UNCLEAR_HANDWRITING'],
    status: 'AI_COMPLETE',
    aiGeneratedAt: '2024-11-15T12:18:00Z',
    version: 1,
  },
  {
    id: 'eval-003',
    submissionId: 'sub-003',
    studentId: 'student-004',
    studentName: 'David Kumar',
    examId: 'exam-001',
    examTitle: 'Data Structures and Algorithms (CS201)',
    transcription:
      'Q1: Stack is LIFO data structure — undo operations in text editors. Queue is FIFO — customer service call centres. Q2a: Binary search algorithm with correct pseudocode. Q2b: O(log n) because we halve the search space. Q3: BST construction for given values. In-order: 8, 10, 12, 15, 18, 20, 25.',
    questions: [
      {
        id: 'eq-003-1',
        questionNumber: '1',
        studentAnswer:
          'Stack is LIFO. Application: undo/redo in text editors. Queue is FIFO. Application: customer service systems where first caller is served first.',
        answerSummary: 'Correct definitions and applications.',
        criteriaScores: [
          { criterionId: 'rc-001-1-1', criterion: 'Correct definition of Stack (LIFO)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-2', criterion: 'Correct definition of Queue (FIFO)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-3', criterion: 'Valid real-world application of Stack', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-4', criterion: 'Valid real-world application of Queue', awarded: 2, max: 2 },
          { criterionId: 'rc-001-1-5', criterion: 'Clarity and quality of explanation', awarded: 1, max: 2 },
        ],
        totalAwarded: 9,
        maxMarks: 10,
        feedback: 'Good answers. Minor deduction for explanation brevity.',
        confidence: 0.89,
        confidenceLevel: 'MEDIUM',
        flags: [],
        pageStart: 1,
        pageEnd: 1,
      },
      {
        id: 'eq-003-2a',
        questionNumber: '2a',
        studentAnswer: 'Binary search pseudocode — correct structure with pointer initialisation.',
        answerSummary: 'Pseudocode provided, partially unclear due to handwriting.',
        criteriaScores: [
          { criterionId: 'rc-001-2a-1', criterion: 'Correct initialisation', awarded: 2, max: 2 },
          { criterionId: 'rc-001-2a-2', criterion: 'Correct loop and mid-point', awarded: 3, max: 3 },
          { criterionId: 'rc-001-2a-3', criterion: 'Correct return statements', awarded: 2, max: 3 },
        ],
        totalAwarded: 7,
        maxMarks: 8,
        feedback: 'Good pseudocode. Return for not-found case unclear in handwriting.',
        confidence: 0.75,
        confidenceLevel: 'MEDIUM',
        flags: ['UNCLEAR_HANDWRITING'],
        pageStart: 2,
        pageEnd: 2,
      },
      {
        id: 'eq-003-2b',
        questionNumber: '2b',
        studentAnswer: 'O(log n). Each step halves search space.',
        answerSummary: 'Correct.',
        criteriaScores: [
          { criterionId: 'rc-001-2b-1', criterion: 'Correct complexity: O(log n)', awarded: 2, max: 2 },
          { criterionId: 'rc-001-2b-2', criterion: 'Correct justification', awarded: 1, max: 2 },
        ],
        totalAwarded: 3,
        maxMarks: 4,
        feedback: 'Correct complexity. Justification needs more depth.',
        confidence: 0.93,
        confidenceLevel: 'HIGH',
        flags: [],
        pageStart: 2,
        pageEnd: 2,
      },
      {
        id: 'eq-003-3',
        questionNumber: '3',
        studentAnswer: 'BST correct. In-order: 8, 10, 12, 15, 18, 20, 25.',
        answerSummary: 'Correct BST and traversal.',
        criteriaScores: [
          { criterionId: 'rc-001-3-1', criterion: 'Correct BST structure', awarded: 4, max: 4 },
          { criterionId: 'rc-001-3-2', criterion: 'Correct in-order traversal', awarded: 2, max: 2 },
          { criterionId: 'rc-001-3-3', criterion: 'Clear diagram', awarded: 2, max: 2 },
        ],
        totalAwarded: 8,
        maxMarks: 8,
        feedback: 'Perfect BST and traversal.',
        confidence: 0.92,
        confidenceLevel: 'HIGH',
        flags: [],
        pageStart: 3,
        pageEnd: 3,
      },
    ],
    totalMarks: 27,
    maxMarks: 30,
    facultyTotalMarks: 27,
    overallConfidence: 0.87,
    overallConfidenceLevel: 'MEDIUM',
    flags: ['UNCLEAR_HANDWRITING'],
    status: 'PUBLISHED',
    aiGeneratedAt: '2024-11-15T12:05:00Z',
    facultyReviewedAt: '2024-11-16T09:30:00Z',
    publishedAt: '2024-11-16T10:00:00Z',
    facultyNotes: 'Good performance overall. Handwriting clarity could be improved.',
    facultyId: 'faculty-001',
    facultyName: 'Prof. Arjun Sharma',
    version: 1,
  },
];

export const DEMO_CALIBRATIONS: CalibrationSample[] = [
  {
    id: 'cal-001',
    studentId: 'student-001',
    imageUrl: 'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=800&h=600&fit=crop&auto=format',
    uploadedAt: '2024-08-05T14:30:00Z',
    qualityScore: 0.91,
    status: 'APPROVED',
  },
  {
    id: 'cal-002',
    studentId: 'student-002',
    imageUrl: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800&h=600&fit=crop&auto=format',
    uploadedAt: '2024-08-06T09:15:00Z',
    qualityScore: 0.84,
    status: 'APPROVED',
  },
  {
    id: 'cal-004',
    studentId: 'student-004',
    imageUrl: 'https://images.unsplash.com/photo-1471107191679-f26174d2d41e?w=800&h=600&fit=crop&auto=format',
    uploadedAt: '2024-08-06T11:00:00Z',
    qualityScore: 0.78,
    status: 'APPROVED',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    userId: 'student-001',
    userName: 'Alice Johnson',
    userRole: 'student',
    action: 'SUBMISSION_CREATED',
    entity: 'submission',
    entityId: 'sub-001',
    details: 'Submitted exam CS201 with 3 pages.',
    timestamp: '2024-11-15T11:45:00Z',
    ipAddress: '192.168.1.42',
  },
  {
    id: 'audit-002',
    userId: 'faculty-001',
    userName: 'Prof. Arjun Sharma',
    userRole: 'faculty',
    action: 'EVALUATION_REVIEWED',
    entity: 'evaluation',
    entityId: 'eval-003',
    details: 'Reviewed and approved evaluation for David Kumar. Total: 27/30.',
    timestamp: '2024-11-16T09:30:00Z',
    ipAddress: '10.0.0.15',
  },
  {
    id: 'audit-003',
    userId: 'faculty-001',
    userName: 'Prof. Arjun Sharma',
    userRole: 'faculty',
    action: 'RESULT_PUBLISHED',
    entity: 'evaluation',
    entityId: 'eval-003',
    details: 'Published result for David Kumar (CS201). Score: 27/30 (90%).',
    timestamp: '2024-11-16T10:00:00Z',
    ipAddress: '10.0.0.15',
  },
  {
    id: 'audit-004',
    userId: 'student-002',
    userName: 'Bob Smith',
    userRole: 'student',
    action: 'SUBMISSION_CREATED',
    entity: 'submission',
    entityId: 'sub-002',
    details: 'Submitted exam CS201 with 2 pages.',
    timestamp: '2024-11-15T12:10:00Z',
    ipAddress: '192.168.1.67',
  },
  {
    id: 'audit-005',
    userId: 'admin-001',
    userName: 'Dr. Priya Nair',
    userRole: 'admin',
    action: 'EXAM_CREATED',
    entity: 'exam',
    entityId: 'exam-001',
    details: 'Exam CS201 created and activated.',
    timestamp: '2024-09-01T10:00:00Z',
    ipAddress: '10.0.0.1',
  },
  {
    id: 'audit-006',
    userId: 'student-004',
    userName: 'David Kumar',
    userRole: 'student',
    action: 'RESULT_VIEWED',
    entity: 'evaluation',
    entityId: 'eval-003',
    details: 'Student viewed published result.',
    timestamp: '2024-11-16T14:22:00Z',
    ipAddress: '192.168.2.11',
  },
];

export const DEMO_AI_USAGE: AIUsageRecord[] = [
  { id: 'usage-001', date: '2024-11-15', requestCount: 3, pageCount: 8, successCount: 3, failureCount: 0 },
  { id: 'usage-002', date: '2024-11-14', requestCount: 1, pageCount: 2, successCount: 1, failureCount: 0 },
  { id: 'usage-003', date: '2024-11-13', requestCount: 2, pageCount: 5, successCount: 2, failureCount: 0 },
  { id: 'usage-004', date: '2024-11-12', requestCount: 0, pageCount: 0, successCount: 0, failureCount: 0 },
  { id: 'usage-005', date: '2024-11-11', requestCount: 4, pageCount: 12, successCount: 3, failureCount: 1 },
  { id: 'usage-006', date: '2024-11-10', requestCount: 2, pageCount: 6, successCount: 2, failureCount: 0 },
  { id: 'usage-007', date: '2024-11-09', requestCount: 1, pageCount: 3, successCount: 1, failureCount: 0 },
];

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  maxAiRequestsPerDay: 50,
  maxAiRequestsPerStudentPerDay: 5,
  maxPagesPerSubmission: 30,
  maxUploadSizeMb: 100,
  highConfidenceThreshold: 0.9,
  mediumConfidenceThreshold: 0.75,
  aiMode: 'demo',
  aiProvider: 'demo',
  groqModel: 'llama-3.2-11b-vision-preview',
};

export const CALIBRATION_PASSAGE = `Please write the following passage in your normal handwriting:

"The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. How vexingly quick daft zebras jump!

Numbers: 0 1 2 3 4 5 6 7 8 9
Symbols: + - × ÷ = < > ( ) [ ] { }

This calibration sample helps our AI better understand your unique handwriting style. Write at your natural pace — there is no need to alter your handwriting. Each letter and character you write helps our system accurately transcribe your examination answers."`;
